### ISSUE TITLE
Groundtruth

### ISSUE THREAD

**Issue by bashar-tom** [Ahmedest61/CNN-Region-VLAD-VPR#1]
thanks for this remarkable work.  
I'm working on the same task for my master thesis and I want to do some tests on these datasets.
Could you please share the groundtruth labels? I want them to have the same evaluation scheme used by you.
Thanks in advance

**Comment by Ahmedest61** [comment]
For ground truth, using GPS information of all the Berlin datasets, matching window was created by taking euclidean difference of each query "lon" and "lat" against all the reference frames' coordinates and top five minimum eculidean distant reference images were kept. Whereas for garden point and synthesized nordland, frame tolerance were kept eight and five frames.
