### ISSUE TITLE
How is the distance measured between GPS coordinates

### ISSUE THREAD

**Issue by amaralibey** [Ahmedest61/CNN-Region-VLAD-VPR#2]
I would like to thank you first for sharing your code, 
I've noticed that the distance between gps coords is the euclidean distance. How can you fix a threshold if you're using an euclidean distance between dergees ? How can you measure 25m using euclidean on gps coordinates ?
Thank you

**Comment by Ahmedest61** [comment]
Please check the following links. I hope it can help you. 
https://www.nhc.noaa.gov/gccalc.shtml 
http://www.meridianoutpost.com/resources/etools/calculators/calculator-latitude-longitude-distance.php?
https://forums.garmin.com/developer/connect-iq/f/discussion/992/anyone-got-a-function-to-get-distance-between-two-lan-lon-using-degrees
https://andrew.hedges.name/experiments/haversine/

**Comment by amaralibey** [comment]
I know how to calculate distance between gps coordinates using haversine distance. I was talking about this piece of code you have used:
`for key1, val1 in values[0].items():

    for key2, val2 in values[1].items():
            dif[key2] = math.sqrt(sum([(a - b)**2 for a, b in zip(val1, val2)]))
        path1[key1] = list(OrderedDict(sorted(dif.items(), key=operator.itemgetter(1),reverse=False)).keys())[:5]  
        dif.clear()`

You're actually using euclidean distance on gps coordinates which should not be the case unless you convert the coordinates to UTM.
