### ISSUE TITLE
How to calculate the predictionScore

### ISSUE THREAD

**Issue by zhangcaocao** [Ahmedest61/CNN-Region-VLAD-VPR#3]
Hello. First, thanks for your contribution with this repo.

Would you please tell me how to calculate the predictionScore in the source code :https://github.com/Ahmedest61/CNN-Region-VLAD-VPR/blob/fb823424dbe40cb3cce3be4d15b056def81f4cac/produceResults.py#L58

**Comment by Ahmedest61** [comment]
It's the maximum matching score for a query against the matched reference image. I have uploaded the source code, please have a look. Thank you!
