### ISSUE TITLE
New vocabulary

### ISSUE THREAD

**Issue by christina284** [Ahmedest61/CNN-Region-VLAD-VPR#4]
Thank you for the great work! I was wondering how can i create a new vocabulary to use?

**Comment by Ahmedest61** [comment]
Pass down (let say 2000) images, get required number of ROIs from each image (e.g., N=200 or N=400) and store/load/cluster all the ROIs into clusters (128 or 256) using KMeans?

**Comment by christina284** [comment]
Yes, thank you, that is what i did.

**Comment by Ahmedest61** [comment]
Glad you solved it. Cheers!
