### ISSUE TITLE
when got N ROI regions in the feature map, how to get the corresponding ROI in the original image

### ISSUE THREAD

**Issue by HawkYJH** [Ahmedest61/CNN-Region-VLAD-VPR#5]
when got N ROI regions in the feature map, how to get the corresponding ROI in the original image

**Comment by HawkYJH** [comment]
how to get the result just like showing  in the frontpage.jpg？

**Comment by Ahmedest61** [comment]
Hi, once the top 'N' ROIs are captured from all the feature maps you can just repeat L53-55 (Region-VLAD.py) while utilizing knowledge about top 'N' energetic regions and their bounded areas (x,y). Based on that, assign a value to a dumy 2D numpy/vector of size equal to feature map - bright regions in frontpage.jpg are energetic thus having high value/priority.
